# fly.toml app configuration file generated for backend-winter-brook-140 on 2025-02-25T22:12:52-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-winter-brook-140'
primary_region = 'dfw'

[build]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
